name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate image tag
        run: echo "::set-env name=tag::$(date +%y%m%d)-$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: sepa
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sepa/thanos-kit
          tags: latest,${{ env.tag }}
          add_git_labels: true
