name: CI
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # tests takes too long inside docker arm buildx
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: make test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: sepa
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sepa/thanos-kit
          tags: |
            type=raw,value={{date 'YYMMDD'}}
            type=raw,value={{branch}}-{{sha}}
          flavor: |
            latest=true

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VER=${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max